# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -d -c -r . gs://songsmithstudio.uk
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=1800" gs://songsmithstudio/*.html
